<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">IMPORT from USA, NO-Ok Reciprocal Tariff plan in Effect</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">USA will charge tariff on countries that charge USA. SOUNDS FAIR!</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Targets include China, Japan, South Korea and the European Union.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Why does USA have to outsource jobs internationally &amp; buy from the world? </span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Executive Order below</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Current Tariffs Being on 03/12/25:
</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Steel and aluminum imports
</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">0% tariffs on goods from China
</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">30-day hold on goods from Canada and Mexico.</span></span>

<img title="Download free HD stock image of Port Ship" src="https://cdn.pixabay.com/photo/2021/09/30/17/53/port-6670683_1280.jpg" srcset="https://cdn.pixabay.com/photo/2021/09/30/17/53/port-6670683_960_720.jpg 1x, https://cdn.pixabay.com/photo/2021/09/30/17/53/port-6670683_1280.jpg 2x" alt="Free Port Ship photo and picture" />
<h1 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trump Orders Plans for Reciprocal Tariffs on U.S. Trade Partners</span></span></strong></h1>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">U.S. </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">President Donald Trump</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> has directed his </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">economic team</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> to develop plans for </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">reciprocal tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> on every country that imposes tariffs on U.S. imports. The move, announced </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Thursday</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, significantly raises the likelihood of a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">global trade war</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, potentially affecting both </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">American allies and adversaries</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"On trade, I have decided for purposes of fairness, that I will charge a reciprocal tariff, meaning whatever countries charge the United States of America, we will charge them. No more, no less,"</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> Trump told reporters from the </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Oval Office</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trump’s Memo Orders Tariff Calculations</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trump signed a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">memorandum</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> instructing his team to begin calculating </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> that match those imposed by other nations. The directive also seeks to address </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">non-tariff trade barriers</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, such as </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">vehicle safety regulations that restrict U.S. auto exports</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> and </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">value-added taxes (VAT) that inflate the cost of American goods abroad</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">However, the directive </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">did not immediately impose new tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. Instead, it initiates what could be a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">weeks- or months-long review</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> of the </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">trade levies and policies</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> enforced by foreign governments before the administration formulates its response.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The plan </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">targets major U.S. trading partners</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, including </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">China, Japan, South Korea, and the European Union</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. The announcement has heightened concerns over a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">widening trade war</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> and its potential impact on </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">U.S. inflation</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Commerce Secretary: Final Plan Due by April 1</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Howard Lutnick, Trump’s nominee for </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Commerce Secretary</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, stated that the administration will </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">evaluate each affected country separately</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. He confirmed that </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">studies on reciprocal tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> will be completed by </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">April 1</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">—the deadline Trump set on his </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">first day in office</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> for officials to develop a plan to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">reduce chronic U.S. trade deficits</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trump, who </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">campaigned on lowering consumer prices</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, acknowledged that prices could </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">rise in the short term</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> due to the new tariff policies but defended them, saying, </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"Tariffs are great."</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">A </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">White House official</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, speaking ahead of Trump’s </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Oval Office event</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, emphasized that the administration will focus first on </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">countries with the largest trade surpluses</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> and </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">highest tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trump’s proposed tariffs would </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">match the highest duties</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> charged by other nations and seek to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">counteract restrictive regulations, VAT systems, government subsidies, and currency policies</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> that hinder </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">U.S. exports</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"They effectively don't let us do business. So we're going to put a number on that that is a fair number. We're able to accurately determine the cost of these non-monetary trade barriers,"</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> Trump said.</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">A Strategy to Encourage Trade Negotiations?</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The broad announcement appears to be designed, </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">at least in part</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">pressure</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> other countries into negotiations. The </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">White House official</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> noted that Trump </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">would be willing to lower tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> if foreign governments agreed to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">reduce their own trade barriers</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Rather than a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"one-size-fits-all"</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> approach, the new tariff policy would allow for </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">customized levies</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> based on each country’s trade practices. However, the official did not rule out the possibility of a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">flat global tariff</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"It’s a relief that the administration isn’t rushing to impose new tariffs, and we welcome the president taking a more nuanced, inter-agency approach,"</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> said </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Tiffany Smith</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, Vice President for Global Trade at the </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">National Foreign Trade Council</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"Ideally, this process will result in us working with our trading partners to lower their tariffs and trade barriers as opposed to increasing our own."</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trump’s Expanding Tariff Policy</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Since taking office on </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">January 20</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, Trump has already implemented </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">several major tariff measures</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">:</span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">March 12</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: Tariffs on </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">all steel and aluminum imports</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> will take effect.</span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">China</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: A </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">10% tariff</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> on </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">all Chinese goods</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> has been imposed.</span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Canada &amp; Mexico</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: A </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">30-day hold</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> has been placed on planned tariffs against both countries.</span></span></li>
</ul>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Additionally, Trump recently stated he is considering </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">separate tariffs on cars, semiconductors, and pharmaceuticals</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">On Thursday, he confirmed that auto tariffs will be introduced soon.</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trade Experts: Every Country on Notice</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Josh Lipsky</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, Director of the </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Atlantic Council’s GeoEconomics Center</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> and a former </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">IMF adviser</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, warned that the announcement is a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">serious escalation in U.S. trade policy</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"This is beyond negotiation. It's to be taken very seriously,"</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> Lipsky said. </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"I do think every country has been put on notice. And if you were going to implement reciprocal tariffs on the scale he's talking about, this is actually how you would go about it."</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">India’s Tariffs in the Spotlight</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">During the </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">announcement</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, Trump acknowledged that </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">India imposes the highest tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> on U.S. exports among major trading partners. Indian </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Prime Minister Narendra Modi</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, who was in </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Washington</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> for a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">meeting with Trump</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, oversees a government that has long faced </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">criticism for high import duties on American goods</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>
<h3 class="western"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Legal Hurdles in Implementing Reciprocal Tariffs</span></span></strong></h3>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Structuring Trump’s proposed </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">reciprocal tariffs</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> presents </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">major legal challenges</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. Experts note that his administration may have </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">delayed the announcement</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> earlier in the week as they explored </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">legal pathways</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> to impose the new duties.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Trade lawyers point to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">several possible legal authorities</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> Trump could invoke:</span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Section 122 of the Trade Act of 1974</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: Allows for a </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">flat tariff of up to 15% for six months</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Section 338 of the Tariff Act of 1930</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: Grants authority to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">retaliate against trade discrimination</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> but has </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">never been used</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> before.</span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">International Emergency Economic Powers Act (IEEPA)</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: Previously used to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">justify tariffs on China</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> and </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">pending tariffs on Canada and Mexico</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span></li>
</ul>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">A </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">White House official</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> confirmed that multiple legal mechanisms are under consideration.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">"Absent IEEPA, there would need to be some kind of agency action first before any trade remedy tariffs can be imposed … but everything seems to be on the fast track,"</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> said </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Damon Pike</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">, a trade specialist and principal at </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">BDO International’s U.S. division</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">. He added that under </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">normal circumstances, tariff decisions would be left to Congress</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">—but Trump appears determined to </span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">act swiftly</span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">.</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"><b>EXECUTIVE ORDER READS:</b></span></span>

“<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"><b>Fact Sheet: President Donald J. Trump Announces “Fair and Reciprocal Plan” on Trade </b></span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"><b>February 13, 2025</b></span></span>

<strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">THE “FAIR AND RECIPROCAL PLAN”:</span></span></strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;"> Today, President Donald J. Trump signed a Presidential Memorandum ordering the development of a comprehensive plan for restoring fairness in U.S. trade relationships and countering non-reciprocal trading arrangements.</span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The “Fair and Reciprocal Plan” will seek to correct longstanding imbalances in international trade and ensure fairness across the board. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Gone are the days of America being taken advantage of: this plan will put the American worker first, improve our competitiveness in every area of industry, reduce our trade deficit, and bolster our economic and national security.  </span></span></li>
</ul>
<strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">AMERICA WILL NO LONGER TOLERATE UNFAIR TRADE PRACTICES</span></span></strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: The United States is one of the most open economies in the world, yet our trading partners keep their markets closed to our exports. This lack of reciprocity is unfair and contributes to our large and persistent annual trade deficit.</span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">There are endless examples where our trading partners do not give the United States reciprocal treatment. </span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The U.S. tariff on ethanol is a mere 2.5%. Yet Brazil charges the U.S. ethanol exports a tariff of 18%. As a result, in 2024, the U.S. imported over $200 million in ethanol from Brazil while the U.S. exported only $52 million in ethanol to Brazil. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The U.S. average applied Most Favored Nation (MFN) tariff on agricultural goods is 5%. But India’s average applied MFN tariff is 39%. India also charges a 100% tariff on U.S. motorcycles, while we only charge a 2.4% tariff on Indian motorcycles. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The European Union can export all the shellfish it wants to America. But the EU bans shellfish exports from 48 of our states, despite committing in 2020 to expedite approvals for shellfish exports. As a result, in 2023, the U.S. imported $274 million in shellfish from the EU but exported only $38 million. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The EU also imposes a 10% tariff on imported cars. Yet the U.S. only imposes a 2.5% tariff. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">A 2019 report found that across 132 countries and more than 600,000 product lines, United States exporters face higher tariffs more than two-thirds of the time. </span></span></li>
</ul>
</li>
</ul>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">This lack of reciprocity is one source of America’s large and persistent annual trade deficit in goods: closed markets abroad reduce U.S. exports and open markets at home result in significant imports, both of which undercut American competitiveness. </span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">The United States has run a trade deficit of goods every year since 1975. In 2024, our trade deficit in goods exceeded $1 trillion. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Thanks to the proliferation of non-reciprocal barriers in just the last few years, the U.S. now runs a trade deficit in agriculture, worth around $40 billion in 2024. </span></span></li>
</ul>
</li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Though America has no such thing, and only America should be allowed to tax American firms, trading partners hand American companies a bill for something called a digital service tax. </span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Canada and France use these taxes to each collect over $500 million per year from American companies. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Overall, these non-reciprocal taxes cost America’s firms over $2 billion per year. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Reciprocal tariffs will bring back fairness and prosperity to the distorted international trade system and stop Americans from being taken advantage of. </span></span></li>
</ul>
</li>
</ul>
<strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">THE ART OF THE INTERNATIONAL DEAL</span></span></strong><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">: President Trump continues to deliver on his mandate given to him by the American People to put America First when it comes to trade.</span></span>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">As President Trump said in the Presidential Memorandum on American First Trade Policy on his first day in office, trade policy is a critical component of our economic security and national security. </span></span></li>
</ul>
<ul>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">In his first term, President Trump successfully ended the outdated and unfair NAFTA, replacing it with the historic USMCA to deliver one of the largest wins for American workers. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">When our national security was threatened by a global oversupply of steel and aluminum, President Trump took swift action to protect America’s national security by implementing tariffs on imports of these goods. </span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">In response to China’s intellectual property theft, forced technology transfer, and other unreasonable behavior, President Trump acted with conviction to impose tariffs on imports from China, using that leverage to reach a historic bilateral economic agreement. </span></span></li>
</ul>
<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Just last week, President Trump leveraged tariffs to force Canada and Mexico to make long-overdue changes at our northern and southern borders, ensuring the safety and security of American citizens.”</span></span>

<span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Sources:</span></span>
<ul>
 	<li class="western"><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Fact Sheet: President Donald J. Trump Announces “Fair and Reciprocal Plan” on Trade
<a href="https://www.whitehouse.gov/fact-sheets/2025/02/fact-sheet-president-donald-j-trump-announces-fair-and-reciprocal-plan-on-trade/">https://www.whitehouse.gov/fact-sheets/2025/02/fact-sheet-president-donald-j-trump-announces-fair-and-reciprocal-plan-on-trade/</a></span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span style="font-size: medium;">U.S. </span><span style="font-size: medium;">President Donald Trump</span></span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span style="font-size: medium;">Howard Lutnick</span></span></span></li>
 	<li><span style="font-family: Times New Roman, serif;"><span style="font-size: medium;">Josh Lipsky</span></span></li>
 	<li><a href="https://pixabay.com/users/smartschwarz-17278601/">Smartschwarz</a>, <a href="https://pixabay.com/photos/port-ship-water-sea-crane-freight-6670683/">https://pixabay.com/photos/port-ship-water-sea-crane-freight-6670683/</a>, 02/13/2025</li>
</ul>
Author: Ryan Bridglal, 02/13/2025
